name: Test Workflow
on:
 push:
 workflow_dispatch:
jobs:
    test-job:
        name: unit-testing
        strategy:
            matrix:
                os: [ubuntu-latest]
                ver: [22.21]
        runs-on: ${{matrix.os}}
        steps:
        - name: checkout repository
        uses: actions/checkout@v2  
             
        - name: Set up Node.js
        uses: actions/setup-node@v2
            with:
            node-version: ${{ matrix.ver }}
            
        - name: install dependecies
            run: npm install

        - name: run-tests
            run: npm test
        
        - name: upload results
            uses: actions/upload-artifact@v4
            with:
                # Name of the artifact to upload.
                # Optional. Default is 'artifact'
                name: Mocha-Test-Result

                # A file, directory or wildcard pattern that describes what to upload
                # Required.
                path: test-results.xml


